# Generated by Django 6.0.3 on 2026-05-22 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctionform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('itempicture', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='services/')),
                ('itemcat', models.CharField(max_length=30)),
                ('itembaseprice', models.IntegerField()),
                ('itemdatetoauction', models.DateField()),
                ('itemtimetoauction', models.TimeField()),
                ('itemdescription', models.TextField()),
                ('isactive', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auctiontransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidamount', models.IntegerField()),
                ('bidtime', models.DateTimeField(auto_now_add=True)),
                ('winner', models.BooleanField(default=False)),
                ('auctionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.auctionform')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
